# Generated by Django 5.1.4 on 2024-12-12 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ElectricUsage',
            fields=[
                ('hour', models.DateTimeField(help_text='Start of an hour of electricity usage.', primary_key=True, serialize=False, verbose_name='Hour')),
                ('kwh', models.DecimalField(decimal_places=4, help_text='Amount of electricity used, in kilowatt-hours (kWh), in an hour.', max_digits=7, verbose_name='Kilowatt-Hours (kWh)')),
            ],
            options={
                'verbose_name': 'Electric Usage',
                'verbose_name_plural': 'Electric Usage',
                'db_table': 'electric',
                'ordering': ('hour',),
                'managed': True,
            },
        ),
    ]
