# Generated by Django 5.1.4 on 2024-12-19 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='waterusage',
            options={'managed': True, 'ordering': ('date',), 'verbose_name': 'day', 'verbose_name_plural': 'days'},
        ),
    ]
