# Generated by Django 5.1.4 on 2024-12-27 17:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0002_alter_waterusage_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='waterusage',
            options={'managed': True, 'ordering': ('day',), 'verbose_name': 'day', 'verbose_name_plural': 'days'},
        ),
        migrations.RemoveField(
            model_name='waterusage',
            name='date',
        ),
        migrations.AddField(
            model_name='waterusage',
            name='day',
            field=models.DateField(default=django.utils.timezone.now, help_text='Date of water usage.', primary_key=True, serialize=False, verbose_name='Day'),
            preserve_default=False,
        ),
    ]
