# Generated by Django 5.1.4 on 2024-12-28 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0003_alter_waterusage_options_remove_waterusage_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterusage',
            name='gallons',
            field=models.DecimalField(decimal_places=5, help_text='Amount of water usage in gallons, on the day.', max_digits=10, verbose_name='Gallons'),
        ),
    ]
