# Generated by Django 5.1.4 on 2024-12-15 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GasUsage',
            fields=[
                ('month', models.DateField(help_text='Billing month of natural gas usage.', primary_key=True, serialize=False, verbose_name='Month')),
                ('ccf', models.DecimalField(decimal_places=2, help_text='Amount of natural gas used, in hundreds of cubic feet (CCF), in a month.', max_digits=5, verbose_name='Hundreds of Cubic Feet (CCF)')),
            ],
            options={
                'verbose_name': 'Natural Gas Usage',
                'verbose_name_plural': 'Natural Gas Usage',
                'db_table': 'gas',
                'ordering': ('month',),
                'managed': True,
            },
        ),
    ]
