# Generated by Django 5.1.4 on 2024-12-19 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('natural_gas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gasusage',
            options={'managed': True, 'ordering': ('month',), 'verbose_name': 'month', 'verbose_name_plural': 'months'},
        ),
    ]
