# Generated by Django 5.1.4 on 2024-12-26 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('natural_gas', '0002_alter_gasusage_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GasUsage',
            new_name='NaturalGasUsage',
        ),
        migrations.AlterModelTable(
            name='naturalgasusage',
            table='natural_gas',
        ),
    ]
